import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

import { BsArrowLeftRight } from "react-icons/bs";
import { Container } from "@mantine/core";

import mixpanel from "@/lib/mixpanel";

const Home: NextPage = () => {
  const router = useRouter();

  useEffect(() => {
    mixpanel.track("Landing Hit");
  }, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container size="md">
        <div className="flex items-center gap-2">
          <BsArrowLeftRight className="h-6 w-6 text-orange-400" />
          <h1 className="font-bold text-orange-400">Trueky</h1>
        </div>
      </Container>
      <Container size="md" className="flex flex-col">
        <h1 className="mx-auto max-w-3xl text-center text-3xl">
          Consigue las cosas que quieres pagando con lo que ya tienes
        </h1>

        <section className="grid gap-4 md:grid-cols-3">
          <article className="rounded-lg bg-gray-50 p-4 shadow-[5px_5px_0px_0px_rgba(240,118,164)]">
            Publica tus productos a intercambiar
          </article>
          <article className="rounded-lg bg-gray-50 p-4 shadow-[5px_5px_0px_0px_rgba(240,118,164)]">
            Encuentra productos que te interesen
          </article>
          <article className="rounded-lg bg-gray-50 p-4 shadow-[5px_5px_0px_0px_rgba(240,118,164)]">
            Si alguien más tiene interés en tus productos y hay coincidencia con
            lo que quieres. Tienes un trueque{" "}
          </article>
        </section>

        <button
          className="my-8 mx-auto w-full max-w-md cursor-pointer rounded-full border-none bg-gradient-to-tr from-primary to-secondary py-4 px-12 text-lg font-bold text-white transition-all hover:scale-105 active:scale-100"
          onClick={() => router.push("/ingresar")}
        >
          Ingresar
        </button>
      </Container>
    </>
  );
};

export default Home;
